env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Publish Process

# ↓ 自動生成 下載檔案 及 javadoc
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        id: checkout-source
        uses: actions/checkout@v2
      - name: 'maven jar publish'
        uses: eric2788/maven-jar-publish@master
        with:
         java-version: 18
         pre-release: true
         body: test
         upload-module: './eldependenci-rpc-plugin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Update javadocs'
        id: update-javadoc
        uses: eric2788/push-javadoc-branch@main
        with:
          use-maven: true
          javadocs: javadocs
  upload_github_pkg:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
